class AddIndexes < ActiveRecord::Migration[5.1]
  def change
    add_index :schools, :address
    add_index :schools, :admin0
    add_index :schools, :admin1
    add_index :schools, :admin2
    add_index :schools, :admin3
    add_index :schools, :admin4
    add_index :schools, :admin_code
    add_index :schools, :admin_id
    add_index :schools, :altitude
    add_index :schools, :availability_connectivity
    add_index :schools, :connectivity
    add_index :schools, :country_code
    add_index :schools, :datasource
    add_index :schools, :description
    add_index :schools, :educ_level
    add_index :schools, :electricity
    add_index :schools, :environment
    add_index :schools, :frequency
    add_index :schools, :latency_connectivity
    add_index :schools, :lat
    add_index :schools, :lon
    add_index :schools, :name
    add_index :schools, :num_classrooms
    add_index :schools, :num_latrines
    add_index :schools, :num_teachers
    add_index :schools, :num_students
    add_index :schools, :num_sections
    add_index :schools, :speed_connectivity
    add_index :schools, :type_connectivity
    add_index :schools, :type_school
    add_index :schools, :water
    add_index :schools, :address2
    add_index :schools, :person_contact
    add_index :schools, :email
    add_index :schools, :geoloc_confidence
    add_index :schools, :tower_dist
    add_index :schools, :tower_type_service
    add_index :schools, :tower_type
    add_index :schools, :tower_code
    add_index :schools, :tower_latitude
    add_index :schools, :tower_longitude
    add_index :schools, :owner
    add_index :schools, :provider
    add_index :schools, :is_private
    add_index :schools, :provider_is_private
  end
end
